### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by finne26** [bayvakoof/civstats-app#5]
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
   at civstats.Serializer..ctor()
   at civstats.Program.Main(String[] args)

Followed by a crash

**Comment by bayvakoof** [comment]
Make sure you extract everything in the zip before you run civstats.exe. So please confirm the folder you're running from looks something like:

```
civstats-app-beta/
    civstats.exe
    EntityFramework.dll
    ... (some more .dll files)
    Newtonsoft.Json.dll
    x64/
    x86/
```

From the error you got it appears the `Newtonsoft.Json.dll` file is missing, but if you've checked and it's definitely there try downloading the zip again and re-extracting (maybe the download was corrupted?). Let me know if that doesn't help.

**Comment by finne26** [comment]
Thanks for your quick reply. I think the issue must have been with making a
shortcut - I accidentally left the shortcut in the folder and dragged the
exe itself to my desktop.

Thanks again! It appears to be working now!
